### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by akhror-valiev**
Checking linters

### CODE REVIEW

**Review by victorokoroji — CHANGES_REQUESTED** [review]
Hi @akhror-valiev, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Top highlight 🎯

- Linters are working properly ✅ 


 ## Required Changes ♻️

- [ ] Kindly make sure your readme is descriptive and follows the format used in Microverse which can be seen [here](https://github.com/microverseinc/readme-template) 🙏

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by bimbolabuari — COMMENTED** [review]
Hello @akhror-valiev  👋,

_This is an additional review as a result of the second opinion request._

- Nice implementing most of all the project requirements 👍, however, it is important to have a descriptive and professional README as it is the first file the recruiters and developers see when they encounter your project, so it should be fairly brief but detailed. It will make your project stand out from a bunch of others. 
- As the previous CR pointed out, here is a [Microverse README template](https://github.com/microverseinc/readme-template) you can use to update yours.


- [Optional] I suggest you have a more descriptive PR also 👍 

Keep rocking 🚀!

**Review by aimalamiri — CHANGES_REQUESTED** [review]
Hi @akhror-valiev, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

AlmostThereReachGIF


 ## Highlights
As the previous reviewer and senior code reviewer mentioned, it's important to have a descriptive README file in your repository. So please add a descriptive README file, you can use this [README Template](https://github.com/microverseinc/readme-template) by Microverse.

## Required Changes ♻️


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by akhror-valiev** [comment]
I HAVE ADDED README.MD FILE PLSSSSSSSSSS CHECK

**Comment by akhror-valiev** [comment]
EVERY REVIEWER HAS ANSWER ALMOST THERE. PLS PAY ATTENTION LOOK AT CLOSER

**Comment by akhror-valiev** [comment]
I HAVE ADDED README.MD FILE IN THE MAIN  BRANCH

**Comment by akhror-valiev** [comment]
it is not fair guys, all of you have same answer almost there !

**Comment by akhror-valiev** [comment]
@bimbolabuari why are you guys all of you different? I do not know which of you are right, you told that optinali can make my own but @aimalamiri  told it should be same ...guys pls talk each other

**Comment by akhror-valiev** [comment]
this was my third try and I am almost THERE

**Review by nicupop729 — COMMENTED** [review]
Hello @akhror-valiev  👋,

_This is an additional review as a result of the second opinion request._

First of all, welcome to Microverse! :confetti_ball: 

And kudos for the good work you have done! :clap: 

Please note the followings:
- Yes, README is very important because with these READMEs you "sell" your projects, you will show it off in front of recruiters.
- from now on, please remember that the first thing that reviewers will check is the README, in each and every project here at Microverse;
- you should NEVER push commits into main, but only into feature branches;
- previous reviewers asked for changes because your README was not created in the correct branch, but in the main branch (bad practice);
- the main branch is updated only when the feature branch is approved and you merge it into the main;

You will get used to this flow of work, please don't take it so hard from your first week here; you will see, that it's not so hard, but the basics are learned in the Portal Module.

Because it's your first project and because you had a very full day, I gladly can say that your project is ready to be approved.

Please though, don't repeat the same mistakes for the next projects: always work only in the feature branch, and not in the main, and always create the README file in the first feature branch.

As this was the only reason that your project was not approved it will be approved as soon as possible.
Please note that since we will approve it manually so this could take a few hours!

Keep rocking 🚀!

**Comment by bimbolabuari** [comment]
@akhror-valiev, I requested you update the README in the main branch during the second opinion because it was not updated. But I can see you already updated it, Nice job 👍

**Comment by akhror-valiev** [comment]
**Thanks**,  @nicupop729 @bimbolabuari Now, I have a good insight about README.md and managing branches so that I can not repeat the same mistake in my next projects. I much appreciated it!

**Pull request merged**
